[build]
  command = "npm run build"
  # Plugin will populate .netlify/output/public
  # postbuild script creates the directory structure on Netlify only
  publish = ".netlify/output/public"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

