[build]
  command = "npm run build"
  # Override UI setting - plugin will create and populate this directory
  # Setting this in netlify.toml overrides the UI setting (which is set to "build")
  publish = ".netlify/output/public"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

